# https://github.com/repository-settings/app
_extends: .github
repository:
  name: dnd-sort-position
  description: Get and maintain sort positions for manually sorted lists.
  homepage: https://saiichihashimoto.github.io/dnd-sort-position/
  private: false
branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - Build
          - Lint
          - Test
